### ISSUE TITLE
build failed with the ubuntu18.04 Dockerfile

### ISSUE THREAD

**Issue by syan10** [occlum/occlum#107]
I'm following the wiki to build/run the occlum in a docker by the cmds:
./build_image.sh 0.13.0 ubuntu18.04

but get this below error:
"
CC <= /root/occlum/build/src/run/main.o
/usr/local/bin/ld: /root/occlum/build/lib/libocclum-pal.so: undefined reference to `dlopen'
/usr/local/bin/ld: /root/occlum/build/lib/libocclum-pal.so: undefined reference to `dlerror'
/usr/local/bin/ld: /root/occlum/build/lib/libocclum-pal.so: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
make[2]: *** [/root/occlum/build/bin/occlum-run] Error 1
Makefile:22: recipe for target '/root/occlum/build/bin/occlum-run' failed
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:58: recipe for target 'src' failed
make: *** [src] Error 2
The command '/bin/sh -c git clone https://github.com/occlum/occlum &&     cd occlum &&     make submodule &&     OCCLUM_RELEASE_BUILD=1 make &&     make install &&     cp -r demos /root/demos &&     rm -rf /root/occlum' returned a non-zero code: 2"

anyone who met this issue?

**Comment by tatetian** [comment]
Sorry, this is a regression introduced by [the latest commit](https://github.com/occlum/linux-sgx/commit/a16f69d5ac31a7f1104b37fcd4865bc63faa4820) to Occlum's fork of Intel SGX SDK. It can be fixed in one of the two ways.

1. Drop the commit mentioned above and rebuild Intel SGX SDK.

2. Change one line in`<occlum>/src/run/Makefile` as shown below:
```diff
- LINK_FLAGS := $(SGX_LFLAGS_U) -L$(BUILD_DIR)/lib -lsgx_uprotected_fs -locclum-pal
+ LINK_FLAGS := $(SGX_LFLAGS_U) -L$(BUILD_DIR)/lib -lsgx_uprotected_fs -locclum-pal -ldl 
```

We will fix this bug permanently.

**Comment by guzongmin** [comment]
@syan10 Thanks for your reporting. The issue has been fixed.
