### ISSUE TITLE
offline build failed with release version

### ISSUE THREAD

**Issue by xuchunmei000** [occlum/occlum#108]
I download the release version from https://github.com/occlum/occlum/archive/0.13.0.tar.gz and unzip.
when exec "make submodule", will get error like this:
# make submodule
find: ‘.git/hooks’: No such file or directory
make: *** [githooks] Error 1

my build environment is offline, and cannot connect to netwok while build, so can occlum vendor the dependencies like rust release, refer to https://github.com/rust-lang/rust/pull/39728

**Comment by tatetian** [comment]
Since the repo is downloaded in a zip file, it is no surprise that `.git/hooks` is missing. But that is not essential. The `githooks` target in `<occlum>/Makefile` can be simply commented out.

The real problem is that you want to build Occlum entirely offline. This would be quite difficult as the core of Occlum is a Rust project. And Rust projects are built with Cargo, which needs to download dependent Rust crates. I don't think this requirement can be easily workaround. I recommend that you work with your internet connectivity problem.

By the way, Occlum can be built on x86 platforms without SGX support, as demonstrated by Occlum's Travis CI workflow.

**Comment by xuchunmei000** [comment]
Rust itself is built with Cargo, but its release version contains all the vendor, and I can compile  rust offline.
just suggest to use cargo-vendor to download dependent rust crates when create src dist tarballs.

**Comment by guzongmin** [comment]
@xuchunmei000 Thanks for your sugestion. The new installer is on the way.
