### ISSUE TITLE
Support DCAP attestation

### ISSUE THREAD

**Issue by Ram-srini** [occlum/occlum#127]
Is occlum supports data center attestation primitives(DCAP)?

**Comment by tatetian** [comment]
No, not yet.

Are you asking this for Avalon? If so, we can make this feature request a high priority task.

**Comment by Ram-srini** [comment]
> No, not yet.
> 
> Are you asking this for Avalon? If so, we can make this feature request a high priority task.

Yes it is for Avalon.

**Comment by srieyulianti** [comment]
Hi occlum team, when do you plan to release the DCAP remote attestation demo? I saw that your team have put it in the pull-request?
Thanks

**Comment by guzongmin** [comment]
> Hi occlum team, when do you plan to release the DCAP remote attestation demo? I saw that your team have put it in the pull-request.
> Thanks

We plan to release a Rust version DCAP sample code. Anyway, if you want to use DCAP now, https://github.com/occlum/occlum/pull/330 is a working version.

**Comment by srieyulianti** [comment]
> > Hi occlum team, when do you plan to release the DCAP remote attestation demo? I saw that your team have put it in the pull-request.
> > Thanks
> 
> We plan to release a Rust version DCAP sample code. Anyway, if you want to use DCAP now, #330 is a working version.

Hi, thanks for the quick response. 
I am wondering whether is there a way to generate a file of Quote (quote.dat) as implemented by SGX_DCAP in this link https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode/QuoteVerificationSample? So that the quote verification can run on a different platform/container and verifies the Quote by parsing the "quote.dat" file.

The current implementation of DCAP attestation with Occlum is really helpful, but both the Quote Generation and Quote Verification need to perform on the same platform. It is not well-suited for the real simulation where both parties are running on different containers.
Thanks~

**Comment by guzongmin** [comment]
@srieyulianti You are able to write the file into "/host" folder. It is a host folder which means the host OS is able to access this folder.

**Comment by srieyulianti** [comment]
@guzongmin , thank's a lot for the guide. Yes, I am able to write the file. Now I can verify the quote remotely.:)

Best Regard,
Sri

**Comment by guzongmin** [comment]
DCAP demo is checked in.
