### ISSUE TITLE
how could I build a correct occlum forked intel sgx sdk instead of the one shipped in docker image?

### ISSUE THREAD

**Issue by hxiaodon** [occlum/occlum#128]
Hi,
I tried building the occlum at my dev machine

```
[root@iZ2zecyoti841p69dlab8bZ occlum]# make submodule
Add Git hooks that check Rust code format issues before commits and pushes
git submodule init
git submodule update  
cd deps/rust-sgx-sdk && git apply ../rust-sgx-sdk.patch >/dev/null 2>&1 || git apply ../rust-sgx-sdk.patch -R --check
cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
GEN <=  /data/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
CC <= /data/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
CXX <= /data/occlum/build/internal/tools/protect-integrity/App/App.o
/usr/bin/ld: 找不到 -lsgx_urts_sim_with_se_event
```
Per the [readme doc](https://github.com/occlum/occlum/tree/master/tools/protect-integrity), I should build with https://github.com/occlum/linux-sgx
But when finished, the relevant static sgx lib is still missing

I do find the static lib(libsgx_urts_sim_with_se_event.a) from occlum/occlum:0.15.1-ubuntu18.04 image, could someone tell me how to solve this problem?

**Comment by hxiaodon** [comment]
Should use the v0.13.0 branch for the static lib

**Comment by qqbrother** [comment]
> Should use the v0.13.0 branch for the static lib

Hi, hxiaodon! Did you build the occlum successfully? I have tried to use the v0.13.0 branch and followed the suggestion from [issues/94](https://github.com/occlum/occlum/issues/94) to build Occlum's fork of Intel SGX SDK. However, when I execute the commond 'make submodule', there is another error as follows:
`Add Git hooks that check Rust code format issues before commits and pushes
git submodule init
git submodule update  --progress
cd deps/rust-sgx-sdk && git apply ../rust-sgx-sdk.patch >/dev/null 2>&1 || git apply ../rust-sgx-sdk.patch -R --check
cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
GEN <=  /home/gudale/gudale-dev/occlum/build_sim/tools/protect-integrity/App/Enclave_u.c
CC <= /home/gudale/gudale-dev/occlum/build_sim/tools/protect-integrity/App/Enclave_u.o
CXX <= /home/gudale/gudale-dev/occlum/build_sim/tools/protect-integrity/App/App.o
LINK =>  /home/gudale/gudale-dev/occlum/build_sim/bin/occlum-protect-integrity
GEN <=  /home/gudale/gudale-dev/occlum/build_sim/tools/protect-integrity/Enclave/Enclave_t.c
CXX <=  /home/gudale/gudale-dev/occlum/build_sim/tools/protect-integrity/Enclave/Enclave_t.o
CXX <=  /home/gudale/gudale-dev/occlum/build_sim/tools/protect-integrity/Enclave/Enclave.o
LINK =>  /home/gudale/gudale-dev/occlum/build_sim/lib/occlum-protect-integrity.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>10</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 10, tcs_max_num 10, tcs_min_pool 1
The required memory is 4329472B.
The required memory is 0x421000, 4228 KB.
Succeed.
SIGN =>  /home/gudale/gudale-dev/occlum/build_sim/lib/occlum-protect-integrity.signed.so
/bin/sh: 1: cargo: not found
Makefile:15: recipe for target 'all' failed
make[2]: *** [all] Error 127
Makefile:12: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:27: recipe for target 'submodule' failed
make: *** [submodule] Error 2`
Have you met this problem?

**Comment by qqbrother** [comment]
> Should use the v0.13.0 branch for the static lib

Hi, I have met the same problem when I tried to "make submodule". And I have followed your suggestion that use the v0.13.0 branch to build the project. However, I have met another problem as follows. Could you build occlum successfully with the v0.13.0 branch?

`warning: unused `#[macro_use]` import
 --> /home/gudale/gudale-dev/occlum/deps/sefs/rcore-fs-ramfs/src/lib.rs:4:1
  |
4 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

   Compiling rcore-fs-sfs v0.1.0 (/home/gudale/gudale-dev/occlum/deps/sefs/rcore-fs-sfs)
   Compiling quote v0.6.13
   Compiling rand_os v0.1.3
warning: 1 warning emitted

   Compiling memchr v0.1.11
   Compiling atty v0.2.14
   Compiling time v0.1.44
   Compiling sgx_urts v1.1.0
   Compiling dirs v1.0.5
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/gudale/.cargo/registry/src/github.com-1ecc6299db9ec823/sgx_urts-1.1.0/src/lib.rs:19:1
   |
19 | #![feature(ptr_offset_from)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `sgx_urts`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:142: recipe for target 'bin/sefs-fuse' failed
make[1]: *** [bin/sefs-fuse] Error 101
Makefile:27: recipe for target 'submodule' failed
make: *** [submodule] Error 2`
