### ISSUE TITLE
[BUG] invalid start or end

### ISSUE THREAD

**Issue by fixcik** [occlum/occlum#1420]
Hello, Occlum team!

I found bug:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Embedded((EINVAL, "invalid start or end")), location: Some(ErrorLocation { line: 12, file: "src/vm/vm_range.rs" }), cause: None }', src/vm/vm_manager.rs:879:80
```

Occlum log:
https://gist.githubusercontent.com/fixcik/5b8c7311a9453c6809c9b075c636d7de/raw/605d1d44ee54156be9b4e2604a30a6c9b42dbcba/occlum.end.log

Possible solution/Implementation:
I tried to make a naive fix:
https://github.com/aggregion/occlum/commit/77b4cbe0be35056934ee0806d20a744f2a915594#diff-af4ce17b53c1c616f29d5707a65f3985b6c58fb428cc670302d80a01294b8d24
But got other error (but later, maybe it is related with my fix):
[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 1487) with error code 0x1009: Unknown SGX error (line 21, file src/ocalls/spawn.c)
In some cases i got freezes...

I can prepare working sample if needed.

**Comment by jessehui** [comment]
@fixcik Thanks for using Occlum. Please provide the sample to reproduce this error.

**Comment by fixcik** [comment]
Thank you for Occlum and prompt answers, here is an example: https://github.com/fixcik/occlum-chdb
I also received a similar error when working with big data in [polars](https://github.com/pola-rs/polars/)

**Comment by jessehui** [comment]
I follow the step here: https://github.com/fixcik/occlum-chdb/blob/master/README.md

**Comment by jessehui** [comment]
@fixcik Thank you for reporting this. It turns out it is a bug related to concurrent mprotect. I believe the patch below can fix it: https://github.com/jessehui/occlum/commit/58137c6b9e5ca9f45d81d28c2f87b4de2d17061d. Please also include the support for capget to run chdb. It works in my environment:
![截屏2023-10-25 16 04 03](https://github.com/occlum/occlum/assets/13930406/c030b752-cdd1-4dbf-91b5-3985404a3f89)

Plus, do you guys have any plans to upstream the support for capget? We would really appreciate it!

**Comment by fixcik** [comment]
Thank you very much! I tested fix and it works fine. I've made a pull request to add capget.
