### ISSUE TITLE
Is occlum under active development?

### ISSUE THREAD

**Issue by LeoneChen** [occlum/occlum#1624]
It seems that many bugs proposed in issues are not fixed? So many not closed bug issues.

**Comment by qzheng527** [comment]
@LeoneChen Occlum is under active development. The current  main development branch is 0.31.0-rc.
For reported issues, we are watching and addressing in our pace.
Generally, for any reproted issues, please provide detail logs （Occlum debug/trace log）and HW platforms.
Also, please do development on SGX2 as much as possible since SGX1 is fading way.

**Comment by LeoneChen** [comment]
Thanks very much!

I have another question, will these unexpected behaviors influent my applications run above occlum? Cause my applications get wrong result?

![1729482076597](https://github.com/user-attachments/assets/eddd418a-c7a1-4568-88d1-7c82c1d517d5)

**Comment by jessehui** [comment]
@LeoneChen Thank you for highlighting this issue. I'll look into it. Shared memory is not supported very well on Occlum because of its architecture. However, since we've supported many mainstream applications, most of the problems mentioned might not affect yours. Please try running your application to see if it works as expected. If you encounter any issues, feel free to send us your application along with the steps to reproduce the problem.

**Comment by LeoneChen** [comment]
Thanks very much for your answer. I have no more questions currently, so I will close this issue
