### ISSUE TITLE
Building Occlum from the latest source code: sgx_occlum_utils.edl not found

### ISSUE THREAD

**Issue by b-64rry** [occlum/occlum#265]
Hi,

awesome work with Occlum. Thank you for contributing to it.

The Occlum packages work fine. 
However, building Occlum from the latest source gives me the following error message:

`"File not found within search paths: sgx_occlum_utils.edl"`

Can't find the file in the checkout.
Am I missing something? I am also using Occlum's fork of Intel's SGX SDK

**Comment by guzongmin** [comment]
The sgx_occlum_utils.edl is in the Occlum enhanced SGX SDK. Since you already installed that SDK, I guess you may not run "source environment" in the SDK installed folder.
I strongly recommend you to build Occlum in the prebuilt Occlum docker image (occlum/occlum:0.18.1-ubuntu18.04). It would help you save a lot of time.

**Comment by b-64rry** [comment]
Well, where is the fun of it if everything is prepared for you ;)
I missed the Occlum branch in your fork of the SDK.
Should have looked closer at your docker files. 
That solved it for me, thank you.
