### ISSUE TITLE
SEFS: File System Rollbacks

### ISSUE THREAD

**Issue by Nirusu** [occlum/occlum#341]
Hey,

whilst playing around with the SQLite demo provided with Occlum, I noticed one characteristic about the file system which seems somewhat concerning to me.

From my experiments, the file system seems to be susceptible to rollback attacks, where the host can either rollback the whole filesystem to a previous state (everything under `run/mount/__ROOT`), or even just single blocks from the file system (single encrypted files under `run/mount/_ROOT`). 

While the former once seems somewhat expectable, the latter one seems kind of dangerous as it may allow the host to create an arbitrary state which has not previously existed in the enclave as a whole.

To illustrate what I mean, here's an example which should not work in my opinion, but actually does:
```bash
# Show initial content in database
root@aaf4129ce32a:~/demos/sqlite/occlum_instance# occlum run /bin/sqlite_demo /root/company.db "SELECT * FROM COMPANY"
ID = 1
NAME = Kris
AGE = 27
ADDRESS = California
SALARY = 16000.0
# Save encrypted SEFS block containing the database (previously determined by looking at the file sizes)
root@aaf4129ce32a:~/demos/sqlite/occlum_instance/run/mount/__ROOT# cp 113ff47d82d71240595af389c5a88f45 ../
# Delete the table COMPANY
root@aaf4129ce32a:~/demos/sqlite/occlum_instance# occlum run /bin/sqlite_demo /root/company.db "DROP TABLE COMPANY"
Execute sql-statement: "DROP TABLE COMPANY"
on database: /root/company.db OK
# Check if the table is actually gone... it is
root@aaf4129ce32a:~/demos/sqlite/occlum_instance# occlum run /bin/sqlite_demo /root/company.db "SELECT * FROM COMPANY"
SQL error: no such table: COMPANY
# Rollback the previously saved SEFS block without touching the metadata or other blocks
root@aaf4129ce32a:~/demos/sqlite/occlum_instance/run/mount# mv 113ff47d82d71240595af389c5a88f45 __ROOT/.
# Run SQLite in Occlum again... we get the old data back by only restoring one block of the filesystem
root@aaf4129ce32a:~/demos/sqlite/occlum_instance# occlum run /bin/sqlite_demo /root/company.db "SELECT * FROM COMPANY"
ID = 1
NAME = Kris
AGE = 27
ADDRESS = California
SALARY = 16000.0
```

Granted, this scenario is limited as Occlum will crash badly if the inodes stored in `metadata` do not line up with the rolled-back version. Yet, if the filesystem does not change that much or files are separated somewhat ideal across different blocks, I think this scenario could be used to manipulate the data inside the enclave from the host to a certain level.

I think this partial rollback issue could be mitigated by pinning the single block files inside the metadata, however I am interested to hear your opinion on this issue. 

**System information**:
Version: Occlum 0.20.0 (running under Docker: occlum/occlum:0.20.0-ubuntu18.04)
SGX 1 (SGX mode: HW)

**Comment by tatetian** [comment]
Hi @Nirusu, your analysis is correct and we are aware of SEFS's vulnerability to the file-level rollback attacks. But unfortunately, I don't think there is an easy fix (e.g., "pinning the single block files inside the metadata") given the current architecture of SEFS.

As the name of SEFS (Simple Encrypted File System) suggests, we want to keep its implementation simple. To do so, we store SEFS's metadata and file data in separate files on the host OS and protect each individual file using Intel SGX Protected File System Library (I will refer to them as _SGX files_). And instead of maintaining a FS-level journal to ensure the consistency of the entire FS even in face of crashes, we rely on SGX Protected File System Library to guarantee the consistency of each individual SGX files.

With the above design decisions in mind, it is not hard to see that
* The metadata of SEFS and the file data of SEFS files are stored in separate SGX-protected files (I will refer to them as _the metadata SGX file_ and _the file-data SGX files_); and
* The SGX-protected files may not be in sync with each other in face of crashes.

As a result, we cannot check the integrity of file-data SGX files by maintaining their ever-changing MACs in the metadata SGX file---this will greatly increase the odds that a SEFS image fails to open in face of crashes! So (sadly) we choose the lesser evil.

We are fully aware of SEFS's limitations and believe that SEFS needs a new design to fully address its limitations in terms of performance, security, and consistency. So we have started an internal project to develop a brand-new encrypted file system in Rust.

**Comment by Nirusu** [comment]
Hey @tatetian, thanks for the heads-up and insight into the design decisions. Sounds reasonable given that everything is not ready for production so far.

I'll definitely check out the new file system when it's ready for a public release! Always interested to see what your team is working on :)

Feel free to close the issue if you don't want to keep it in your active issues.
