### ISSUE TITLE
Interests on newer rust-sgx-sdk

### ISSUE THREAD

**Issue by dingelish** [occlum/occlum#85]
Hi there, do you have any plan to upgrade rust-sgx-sdk/Intel SGX SDK to v1.0.9/2.6? or v1.1 suite in November.

**Comment by dingelish** [comment]
I can help if you're interested.

**Comment by tatetian** [comment]
Hi @dingelish ,

Glad to meet you here. And thanks for asking. 

Of course. We are interested in upgrading to the latest Rust/Intel SGX SDK for their new features and bug fixes. The problem is that we maintain a fork of Intel SGX SDK, which is extended with some extra abilities required by Occlum. The most notable example is that we extended Intel SGX Protected File System Library with a new integrity-only mode (only protecting the integrity, not the confidentiality of a SGX-protected file). This new mode is enabled via a new [`sgx_fopen_integrity_only`](https://github.com/occlum/linux-sgx/blob/f342083729879b5f0a23bf31b63bc592cc31bac1/common/inc/sgx_tprotected_fs.h#L98) API. So we also [modified Rust SGX SDK slightly](https://github.com/occlum/occlum/blob/master/deps/rust-sgx-sdk.patch) to use this new mode. So, as you can see, upgrading may not be trivial. That's why we don't upgrade the dependent SDKs often.

But maybe now is a good timing to do the upgrade. 

Do you have any suggestions? Tips? Any heads-up about breaking changes from the latest Intel/Rust SGX SDK? (One thing I can think about is that we cannot use the in-tree `serde_json` anymore from Rust SGX SDK.).

Maybe I can sync Occlum's fork of Intel SGX SDK to the latest version from upstream and then you can help with upgrading Occlum to use the latest Rust SGX SDK?

Best,
Tate

**Comment by dingelish** [comment]
I think we probably can support your modifications in rust sgx sdk. And I believe it's a good start for using occlum in teaclave.

@volcano0dr @mssun @m4sterchain how about you?

**Comment by dingelish** [comment]
i think we could make these changes feature gated by `feature = "occlum"` in sgx_tprotected_fs, and sgx_tstd.

**Comment by mssun** [comment]
For the Teaclave platform, occlum is planned as one of our many workers (managed by k8s). So it's okay for occlum to use a different version.

**Comment by mssun** [comment]
Whether to bring in the Occlum is another topic, we are looking to see the attestation details of Occlum.

**Comment by tatetian** [comment]
The basic support for remote attestation is ready. Check out [the tests](https://github.com/occlum/occlum/blob/master/test/ioctl/main.c#L60) for `SGXIOC_GET_EPID_GROUP_ID ` and `SGXIOC_GEN_QUOTE` SGX-related ioctls and [the demo which includes a user-space, remote attestation library that wraps around the ioctls](https://github.com/occlum/occlum/tree/master/demos/remote_attestation).

**Comment by tatetian** [comment]
> i think we could make these changes feature gated by `feature = "occlum"` in sgx_tprotected_fs, and sgx_tstd.

Another option is to upstream Occlum's major enhancement to Intel SGX SDK, i.e., the integrity-only mode of Intel SGX Protected Files, so that Rust SGX SDK can also support the feature by default.

**Comment by tatetian** [comment]
@mssun Thanks for considering integrating Occlum into Teaclave. Here are some features in 0.9.0 release that may be of your interest:
1. The embedded mode. In contrast to the traditional standalone mode where Occlum runs in a dedicated process, the new embedded mode enables Occlum to be loaded (as a shared library) into the user-controlled process of a SGX application (say, the FaaS platform of Teaclave). This gives the users more control on the life cycles of Occlum (with C APIs) and enables a tighter collaboration (through sharing untrusted memory directly) between the untrusted part of the SGX app and the trusted LibOS processes on Occlum inside the enclave.
2. The official python support. Run the Python interpreter and Python packages from Alpine Linux directly on Occlum.
