### ISSUE TITLE
question for occlum

### ISSUE THREAD

**Issue by sqq0216** [occlum/occlum#87]
Can occlum run an application in JAVA or python

**Comment by tatetian** [comment]
From the perspective of syscall coverage, we should be ok to run JVM or Python interpreter on Occlum.

The problem is that, as a design decision, Occlum chooses musl libc over Glibc for musl libc's small TCB (which means more secure). Thus, Occlum only supports musl libc-based apps. But app on most popular Linux distributions (like Ubuntu) are glibc-based. So in general we need to rebuild apps with Occlum's musl libc-based toolchain, which means recompiling JVM or Python interpreter...

To free the users from recompiling apps for Occlum, we will support binary-compatibility with binaries from Alpine Linux, a popular, musl libc-based Linux distribution, in the next release of Occlum (scheduled to launch at the end of this month). With this binary compatibility, JVM or Python interpreter from Alpine Linux should work on Occlum out of box. And we will officially support Java and Python in subsequent releases.

**Comment by sqq0216** [comment]
Is there a new release of Occlum that support JVM or Python interpreter?
thanks

**Comment by tatetian** [comment]
Official support for Python will come out in the next release. We already have an internal version of Occlum that works with Python 2 and 3. JVM is more complicated. Our plan is to support JVM by the end of Jan or early Feb, 2020.

**Comment by sqq0216** [comment]
Where can I get The paper Occlum: Secure and Efficient Multitasking Inside a Single Enclave of Intel SGX?
I want to know more infomation about Occlum.
thanks!

**Comment by tatetian** [comment]
We will release the final version of the paper available in the middle of Jan, 2019.

**Comment by sqq0216** [comment]
2019 or 2020?
thanks for your answer very much!

**Comment by Yourens** [comment]
Certainly 2020. Hongliang always wants to stay young and stay foolish.

**Comment by tatetian** [comment]
LOL. I wish we could have published the paper in 2019.

**Comment by qzheng527** [comment]
Any updates about the release container image based on a Alpine?
Currently the provided image "occlum/occlum:0.10.0-ubuntu18.04" is still ubuntu based.

**Comment by tatetian** [comment]
Check out [the Python demo](https://github.com/occlum/occlum/tree/master/demos/python). It is an example of how Occlum can leverage Alpine Linux.

**Comment by qzheng527** [comment]
@tatetian Thanks, it is a good example.
But it is still not so convenient.
Is there any plan to provide a apline based occlum image?
Then I could develop my own occlum app based on this alpine occlum image.
And I could use apk commands to install dependent libs/apps directly instead of building it again with musl toolchain.

**Comment by tatetian** [comment]
Our goal is to (eventually) provide an Occlum-compatible, Alpine-based Linux distribution whose apps and packages can be run on Occlum as many as possible. Due to various reasons (e.g., SGX hardware limitations), not all apps from Alpine can be run on Occlum without modifications. There are much work to be done. We will move towards this goal steadily; but it takes time. So stay tuned.

In the meantime, if you would like to use Occlum to some apps from Alpine Linux directly and right now, why not do it yourself 😄  We would be more than happy to take a PR for a Dockerfile based on Alpine Linux.

**Comment by guzongmin** [comment]
The Java and python demo:
https://github.com/occlum/occlum/tree/master/demos/java
https://github.com/occlum/occlum/tree/master/demos/python
